# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - learnmate

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_42ac1d7beeeb4e3c892d3fe41ca63f11 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e4a4a2c4c1db4498b223eba02b7fd850 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_42ac1d7beeeb4e3c892d3fe41ca63f11 }}/backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'learnmate'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e2af3c9063834df1b53d59eb6de11c7a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_42ac1d7beeeb4e3c892d3fe41ca63f11 }}/backend:${{ github.sha }}'